package com.poochiku.suraksha.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURAKSHA_INCIDENT".
 */
public class SurakshaIncident {

    private Long id;
    /** Not-null value. */
    private String reportId;
    private String surakshaId;
    private String username;
    private long latitude;
    private long createdDatetime;
    private long longitude;
    /** Not-null value. */
    private String catName;
    /** Not-null value. */
    private String catType;
    /** Not-null value. */
    private String catDispName;
    /** Not-null value. */
    private String tagName;
    /** Not-null value. */
    private String tafType;
    /** Not-null value. */
    private String tagDispName;
    /** Not-null value. */
    private String desc;
    private String fileIds;

    public SurakshaIncident() {
    }

    public SurakshaIncident(Long id) {
        this.id = id;
    }

    public SurakshaIncident(Long id, String reportId, String surakshaId, String username, long latitude, long createdDatetime, long longitude, String catName, String catType, String catDispName, String tagName, String tafType, String tagDispName, String desc, String fileIds) {
        this.id = id;
        this.reportId = reportId;
        this.surakshaId = surakshaId;
        this.username = username;
        this.latitude = latitude;
        this.createdDatetime = createdDatetime;
        this.longitude = longitude;
        this.catName = catName;
        this.catType = catType;
        this.catDispName = catDispName;
        this.tagName = tagName;
        this.tafType = tafType;
        this.tagDispName = tagDispName;
        this.desc = desc;
        this.fileIds = fileIds;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getReportId() {
        return reportId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    public String getSurakshaId() {
        return surakshaId;
    }

    public void setSurakshaId(String surakshaId) {
        this.surakshaId = surakshaId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public long getLatitude() {
        return latitude;
    }

    public void setLatitude(long latitude) {
        this.latitude = latitude;
    }

    public long getCreatedDatetime() {
        return createdDatetime;
    }

    public void setCreatedDatetime(long createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    public long getLongitude() {
        return longitude;
    }

    public void setLongitude(long longitude) {
        this.longitude = longitude;
    }

    /** Not-null value. */
    public String getCatName() {
        return catName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCatName(String catName) {
        this.catName = catName;
    }

    /** Not-null value. */
    public String getCatType() {
        return catType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCatType(String catType) {
        this.catType = catType;
    }

    /** Not-null value. */
    public String getCatDispName() {
        return catDispName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCatDispName(String catDispName) {
        this.catDispName = catDispName;
    }

    /** Not-null value. */
    public String getTagName() {
        return tagName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /** Not-null value. */
    public String getTafType() {
        return tafType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTafType(String tafType) {
        this.tafType = tafType;
    }

    /** Not-null value. */
    public String getTagDispName() {
        return tagDispName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTagDispName(String tagDispName) {
        this.tagDispName = tagDispName;
    }

    /** Not-null value. */
    public String getDesc() {
        return desc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getFileIds() {
        return fileIds;
    }

    public void setFileIds(String fileIds) {
        this.fileIds = fileIds;
    }

}
