package com.poochiku.suraksha.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.poochiku.suraksha.greenDao.SurakshaUser;
import com.poochiku.suraksha.greenDao.SurakshaIncident;

import com.poochiku.suraksha.greenDao.SurakshaUserDao;
import com.poochiku.suraksha.greenDao.SurakshaIncidentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig surakshaUserDaoConfig;
    private final DaoConfig surakshaIncidentDaoConfig;

    private final SurakshaUserDao surakshaUserDao;
    private final SurakshaIncidentDao surakshaIncidentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        surakshaUserDaoConfig = daoConfigMap.get(SurakshaUserDao.class).clone();
        surakshaUserDaoConfig.initIdentityScope(type);

        surakshaIncidentDaoConfig = daoConfigMap.get(SurakshaIncidentDao.class).clone();
        surakshaIncidentDaoConfig.initIdentityScope(type);

        surakshaUserDao = new SurakshaUserDao(surakshaUserDaoConfig, this);
        surakshaIncidentDao = new SurakshaIncidentDao(surakshaIncidentDaoConfig, this);

        registerDao(SurakshaUser.class, surakshaUserDao);
        registerDao(SurakshaIncident.class, surakshaIncidentDao);
    }
    
    public void clear() {
        surakshaUserDaoConfig.getIdentityScope().clear();
        surakshaIncidentDaoConfig.getIdentityScope().clear();
    }

    public SurakshaUserDao getSurakshaUserDao() {
        return surakshaUserDao;
    }

    public SurakshaIncidentDao getSurakshaIncidentDao() {
        return surakshaIncidentDao;
    }

}
