package com.poochiku.suraksha.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURAKSHA_USER".
 */
public class SurakshaUser {

    private Long id;
    /** Not-null value. */
    private String firstName;
    private String lastName;
    private String email;
    /** Not-null value. */
    private String phoneNumber;
    /** Not-null value. */
    private String gender;
    /** Not-null value. */
    private String surakshaId;
    /** Not-null value. */
    private String password;
    private Long dob;

    public SurakshaUser() {
    }

    public SurakshaUser(Long id) {
        this.id = id;
    }

    public SurakshaUser(Long id, String firstName, String lastName, String email, String phoneNumber, String gender, String surakshaId, String password, Long dob) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.gender = gender;
        this.surakshaId = surakshaId;
        this.password = password;
        this.dob = dob;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirstName() {
        return firstName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /** Not-null value. */
    public String getGender() {
        return gender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /** Not-null value. */
    public String getSurakshaId() {
        return surakshaId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSurakshaId(String surakshaId) {
        this.surakshaId = surakshaId;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    public Long getDob() {
        return dob;
    }

    public void setDob(Long dob) {
        this.dob = dob;
    }

}
